apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab14
  labels:
    app: frontend-lab14
spec:
  selector:
    matchLabels:
      app: frontend-lab14
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab14
    spec:
      containers:
        - name: frontend-lab14
          image: jyseo135/frontend-lab14
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
